apiVersion: backstage.io/v1alpha1
kind: Group

metadata:
  name: kode3
  description: "Time Kode3 Tech"

spec:
  type: teams
  children: []
  profile:
    picture: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEwAAAAxCAYAAABwK080AAAABHNCSVQICAgIfAhkiAAAA3lJREFUaEPl2s1100AQAOCV3oMrSQWQDkwFsTA23EgHeCsg6QAqIKlgTQVwDLGN7QoIFWAqILlykDOrF+XJ8u7OSBpb4+CLD1ImO59m1/ujSDF+3kyNSZVajHt61DQsR6z+1AxjpY6/97Ru2p787yOuQDbBlVJDGw++dRM0jlgWC5Iztj3wPeJCYwErJpg/gLpoHLGKWIXKYEFrDOZKsC4aRywXFidaI7BQgtDI21WsuuNEX1O7/eCHGUF/fu+7n1K1ITCO7lkbjBsrR5KOVgtsW1j7gFYZbNtY0tEqge0KSzIaGWzXWFLRSGBtYUlEQ8HaxpKGFgSTgiUJzQsmDUsKmhNMKpYEtA0w6Vhto62B7QtWm2gPYIB1DovbD56Fb+WFNHXB3fQ+ZO15AxsACbYBQFiwn8F+2vn94l2pt2PTTWM12zcsYqUtr3r6CHswGFqcquSyr+dZhfUnZhZFqusIKrayym0NVRplWyhzKOzSluOvVmo+fq2TaDAxJ7CH+9X1BHJV7OlIuR5AI1UZiharl5Fv7ILSu4B+eyoFg9KO7swcPEnVNbT9+UaFQLLYWPbQxSfmGxTRu3IMiHsWDaZmDheOyxf/xepwnugbSkMl3ePrMTbZfODG2mvhn6bqr+O+hQWDLr7xWcBA6RrTsP/V+vX+zHSiVP10NOQT5PSR2kAYz5aOSvWARerL1Ss9pAaXdp+nCCqBeXrera0w2+2elZL+7ysMXH6DyYuyy6Mbw3xTA7Yx7LH9SsJgbSvjoDxMxLE6ukz0kjJ8QHXZadaJ81cyMEg2PvKnNI7zHl+i8Kv2B15dKHcv578OTV4tejbT900t7DXqLJkz8Tqxtn1qDvOy7IcwA0PWkuLRkF2WXzCd6GAPAV1L3nfp4m7FKVTTZ19gqZWGbUlBN+pgYxeGVcx9bT+M45gee5Kc1zEsyrsdGFZ5ibix47ovaLvAyset4kN27ulLR2sLy8J5T42korWJFQTLphsM72vt25jl6oZolyzeIAWt7crKTdBXBSRUmhQstEtKqDRJWJXA2qg0aViVwXaJJhGrFtgu0KRi1QbbJppkrEZg20CTjtUYDEGrfGoemPORYwUX0wyHO6R5GDZbdyRKTrAcmyOWE40Bi6XC8oQLidbG4oy1hsaExQpmg9kDFXgLaEQ9kg9VLkesDA1esuE8Y70DkiOeODS4njMAAAAASUVORK5CYII=

